# Generated by Django 4.0 on 2022-03-05 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('event_page', '0003_delete_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('img', models.ImageField(blank=True, upload_to='images/')),
                ('img1', models.ImageField(blank=True, upload_to='images/')),
                ('txt1', models.CharField(max_length=200)),
                ('img2', models.ImageField(blank=True, upload_to='images/')),
                ('txt2', models.CharField(max_length=200)),
                ('img3', models.ImageField(blank=True, upload_to='images/')),
                ('txt3', models.CharField(max_length=200)),
                ('extra_description', models.TextField()),
            ],
        ),
    ]
