# Generated by Django 4.0 on 2022-02-28 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('img1', models.ImageField(blank=True, upload_to='images/')),
                ('txt1', models.CharField(blank=True, max_length=200)),
                ('img2', models.ImageField(blank=True, upload_to='images/')),
                ('txt2', models.CharField(blank=True, max_length=200)),
                ('img3', models.ImageField(blank=True, upload_to='images/')),
                ('txt3', models.CharField(blank=True, max_length=200)),
                ('img4', models.ImageField(blank=True, upload_to='images/')),
                ('txt4', models.CharField(blank=True, max_length=200)),
                ('img5', models.ImageField(blank=True, upload_to='images/')),
                ('txt5', models.CharField(blank=True, max_length=200)),
                ('img6', models.ImageField(blank=True, upload_to='images/')),
                ('txt6', models.CharField(blank=True, max_length=200)),
                ('extra_description', models.TextField(blank=True)),
            ],
        ),
    ]
