# Generated by Django 4.0 on 2022-03-05 04:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event_page', '0002_alter_product_img1_alter_product_img2_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='product',
        ),
    ]
