# Generated by Django 4.0 on 2022-04-16 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('img', models.ImageField(blank=True, upload_to='images/')),
                ('img1', models.ImageField(blank=True, upload_to='images/')),
                ('txt1', models.CharField(max_length=200)),
                ('img2', models.ImageField(blank=True, upload_to='images/')),
                ('txt2', models.CharField(max_length=200)),
                ('img3', models.ImageField(blank=True, upload_to='images/')),
                ('txt3', models.CharField(max_length=200)),
                ('extra_description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='GetBooking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('slots', models.CharField(max_length=255)),
                ('user', models.CharField(max_length=255)),
            ],
        ),
    ]
